[package]
name = "aoc_${YEAR}_${DAY}"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
challenges_common.workspace = true
itertools.workspace = true
lazy-regex.workspace = true
