[package]
name = "aoc_2024_13"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
challenges_common.workspace = true
itertools.workspace = true
lazy-regex.workspace = true
regex.workspace = true
once_cell = "1.20.2"
