[workspace]
members = ["challenges_common", "aoc/2022/*"]

[workspace.dependencies]
rpds = "0"
itertools = "0"
challenges_common = { path = "./challenges_common" }
anyhow = "1"
regex = "1"
lazy_static = "1"
petgraph = "0"
