[workspace]
members = [
    "challenges_common",
    "aoc/*/*",
    #    "leetcode/*",
]
resolver = "2"

[workspace.dependencies]
challenges_common = { path = "./challenges_common" }
anyhow = "*"
itertools = "*"
lazy-regex = "*"
regex = "*"
petgraph = "*"
rpds = "*"
lazy_static = "*"
