[workspace]
members = ["challenges_common", "aoc/2022/*"]

[workspace.dependencies]
challenges_common = { path = "./challenges_common" }
anyhow = "1"
itertools = "0"
lazy-regex = "2"
regex = "1"
petgraph = "0"
rpds = "0"
lazy_static = "1"
